name: Dummy Pipeline

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  pull-requests: read

jobs:
  dummy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Show git hash
        run: |
          echo "Git hash: ${GITHUB_SHA}"